services:
  postgres:
    image: postgres:16
    container_name: conversionops-postgres
    environment:
      POSTGRES_USER: rocket
      POSTGRES_PASSWORD: Zzp990812
      POSTGRES_DB: rocket
    ports:
      - "5434:5432"
    volumes:
      - conversionops_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rocket -d rocket"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-12-18T02-57-28Z
    container_name: conversionops-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - conversionops_minio:/data

  airflow:
    image: apache/airflow:2.9.3
    container_name: conversionops-airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://rocket:Zzp990812@postgres:5432/rocket
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./pipelines:/opt/airflow/pipelines
      - ./sql:/opt/airflow/sql
    command: bash -c "airflow db upgrade && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com && airflow webserver & airflow scheduler"

volumes:
  conversionops_pgdata:
  conversionops_minio:
